CREATE DATABASE DATA_APPS_DEMO;
CREATE SCHEMA DATA_APPS_DEMO.DEMO;

CREATE WAREHOUSE DATA_APPS_ADHOC WITH WAREHOUSE_SIZE='small';
USE WAREHOUSE DATA_APPS_ADHOC;

CREATE STAGE "DATA_APPS_DEMO"."DEMO"."DEMOCITIBIKEDATA" 
ENCRYPTION=(TYPE='AWS_SSE_S3')
URL = 's3://demo-citibike-data/';

CREATE ROLE DATA_APPS_DEMO_APP;
GRANT USAGE ON DATABASE DATA_APPS_DEMO TO ROLE DATA_APPS_DEMO_APP;
GRANT USAGE ON SCHEMA DEMO TO ROLE DATA_APPS_DEMO_APP;


create TEMPORARY TABLE TEMP_TRIPS (
	TRIPDURATION NUMBER(38,0),
	STARTTIME TIMESTAMP_NTZ(9),
	STOPTIME TIMESTAMP_NTZ(9),
	START_STATION_ID NUMBER(38,0),
	END_STATION_ID NUMBER(38,0),
	BIKEID NUMBER(38,0),
	USERTYPE VARCHAR(16777216),
	BIRTH_YEAR NUMBER(38,0),
	GENDER NUMBER(38,0)
);

create TEMPORARY TABLE TEMP_WEATHER (
	STATE VARCHAR(80),
	OBSERVATION_DATE DATE,
	DAY_OF_YEAR NUMBER(3,0),
	TEMP_MIN_F NUMBER(5,1),
	TEMP_MAX_F NUMBER(5,1),
	TEMP_AVG_F NUMBER(5,1),
	TEMP_MIN_C FLOAT,
	TEMP_MAX_C FLOAT,
	TEMP_AVG_C FLOAT,
	TOT_PRECIP_IN NUMBER(4,2),
	TOT_SNOWFALL_IN NUMBER(4,2),
	TOT_SNOWDEPTH_IN NUMBER(4,1),
	TOT_PRECIP_MM NUMBER(8,1),
	TOT_SNOWFALL_MM NUMBER(8,1),
	TOT_SNOWDEPTH_MM NUMBER(8,1)
);

COPY INTO TEMP_TRIPS from @DEMO.DEMOCITIBIKEDATA
file_format=(type=csv skip_header=1) pattern='.*trips.*.csv.gz';

DROP TABLE IF EXISTS TRIPS;
CREATE TABLE TRIPS AS
(Select * from TEMP_TRIPS order by STARTTIME);

COPY INTO TEMP_WEATHER from @DEMO.DEMOCITIBIKEDATA 
file_format=(type=csv skip_header=1) pattern='.*weather.*.csv.gz';

DROP TABLE IF EXISTS WEATHER;
CREATE TABLE WEATHER AS
(Select * from TEMP_WEATHER order by OBSERVATION_DATE);

GRANT SELECT ON TABLE WEATHER TO ROLE DATA_APPS_DEMO_APP;
GRANT SELECT ON TABLE TRIPS TO ROLE DATA_APPS_DEMO_APP;

CREATE USER DATA_APPS_DEMO 
DEFAULT_WAREHOUSE=DATA_APPS_DEMO 
DEFAULT_NAMESPACE=DATA_APPS_DEMO.DEMO
DEFAULT_ROLE=DATA_APPS_DEMO_APP
RSA_PUBLIC_KEY='RSA_PUBLIC_KEY_HERE';

GRANT ROLE DATA_APPS_DEMO_APP TO USER DATA_APPS_DEMO;

CREATE WAREHOUSE DATA_APPS_DEMO WITH WAREHOUSE_SIZE='small' STATEMENT_TIMEOUT_IN_SECONDS=5 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS=5;
CREATE WAREHOUSE DATA_APPS_DEMO_MC WITH WAREHOUSE_SIZE='small' MIN_CLUSTER_COUNT=2 MAX_CLUSTER_COUNT=5 STATEMENT_TIMEOUT_IN_SECONDS=5 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS=5;
GRANT USAGE ON WAREHOUSE DATA_APPS_DEMO TO ROLE DATA_APPS_DEMO_APP;
GRANT USAGE ON WAREHOUSE DATA_APPS_DEMO_MC TO ROLE DATA_APPS_DEMO_APP;

CREATE OR REPLACE MATERIALIZED VIEW COUNT_BY_DAY_MVW AS
select COUNT(*) as trip_count, date_trunc('DAY', starttime) as starttime from demo.trips group by date_trunc('DAY', starttime);

CREATE OR REPLACE MATERIALIZED VIEW COUNT_BY_MONTH_MVW AS
select COUNT(*) as trip_count, MONTHNAME(starttime) as month, MIN(starttime) as starttime from demo.trips group by month;
